blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 30
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_arm_blocks = false,
match_block_trailing_comma = true
max_width = 100
merge_imports = true
preserve_block_start_blank_lines = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
space_before_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 30
struct_lit_width = 30
struct_variant_width = 50
trailing_comma = "Never"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
edition = "2018"
